name: Checkout Service CI/CD

on:
  push:
    paths:
      - 'checkout-service/**'
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        cd ${{ github.workspace }}/checkout-service
        npm install

    - name: Build Docker image
      run: |
        cd ${{ github.workspace }}/checkout-service
        docker build -t mega-project/checkout-service:${{ github.sha }} .

  deploy-dry-run:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Helm Lint and Dry-run
      run: |
        cd ${{ github.workspace }}
        helm lint helm-charts/checkout-service
        helm install checkout-service ./helm-charts/checkout-service --dry-run --debug
